# Generated by Django 2.2.6 on 2019-10-29 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mistify_app', '0003_weather'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='spot_un',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
