# Generated by Django 2.2.6 on 2019-10-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mistify_app', '0008_auto_20191029_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='playlist',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
