# Generated by Django 2.2.6 on 2019-10-31 02:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mistify_app', '0010_auto_20191029_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now, max_length=50),
        ),
    ]
