# Generated by Django 2.2.6 on 2019-10-31 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mistify_app', '0014_auto_20191030_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='country',
            field=models.CharField(max_length=2, verbose_name='2-letter Country Code'),
        ),
        migrations.AlterField(
            model_name='result',
            name='datetime',
            field=models.CharField(default='12:11 AM, Oct 4, 2019', max_length=50),
        ),
        migrations.AlterField(
            model_name='result',
            name='spot_un',
            field=models.CharField(max_length=100, verbose_name='spotify Username'),
        ),
    ]
