# Generated by Django 2.2.6 on 2019-10-31 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mistify_app', '0015_auto_20191031_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='datetime',
            field=models.CharField(default='01:16 AM, Oct 4, 2019', max_length=50),
        ),
    ]
