# Generated by Django 2.2.6 on 2019-10-31 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mistify_app', '0016_auto_20191031_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='datetime',
            field=models.CharField(default='02:31 AM, Oct 4, 2019', max_length=50),
        ),
    ]
